// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mclcjtjtdaxcyjuccqlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbGNqdGp0ZGF4Y3lqdWNjcWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MTcwMjcsImV4cCI6MjA1Mjk5MzAyN30.qnMJ4uEUL9wt_otwOo59m54BMUIgN2UBqTPQWlrIzHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);